(function(){
  const nearest=(u,list)=>list.reduce((best,e)=>!best||G.dist(u,e)<G.dist(u,best)?e:best,null);
  const buildings=type=>G.buildings.filter(b=>!b.dead&&!b.hostile&&b.progress>=1&&(!type||b.type===type));
  function go(u,p,state){u.state=state;u.target=null;if(!u.destination||G.dist(u.destination,p)>.8||!u.path.length)G.moveTo(u,p.x,p.y);}
  function wander(u,origin,r){if(!u.path.length){const p=G.nearPoint(origin.x,origin.y,r);go(u,p,u.hero?'Seeking adventure':'Patrolling');}}
  function hero(u){
    if(u.hp<u.maxHp*.43&&u.potions>0){u.potions--;u.hp=Math.min(u.maxHp,u.hp+90);G.fxAt(u.x,u.y,'heal');}
    if(u.hp<u.maxHp*.3||(u.state==='Resting'||u.state==='Fleeing')&&u.hp<u.maxHp*.86){const home=nearest(u,buildings('temple'))||u.home&&!u.home.dead&&u.home||G.palace;if(G.dist(u,home)<3.5){u.state='Resting';u.target=null;u.path=[];u.hp=Math.min(u.maxHp,u.hp+(home.type==='temple'?11:7));}else go(u,home,'Fleeing');return;}
    const close=G.units.filter(e=>!e.dead&&e.hostile&&G.dist(e,u)<u.data.range+3);const enemy=nearest(u,close);
    if(enemy){u.target=enemy;u.state='Fighting '+enemy.data.name;return;}
    if(u.gold>=18&&u.potions<2){const shop=nearest(u,buildings('marketplace'));if(shop&&(G.dist(u,shop)<9||!u.goal)){if(G.dist(u,shop)<3){const count=Math.min(2-u.potions,Math.floor(u.gold/18));u.potions+=count;u.gold-=count*18;shop.taxPool+=count*18;u.hp=Math.min(u.maxHp,u.hp+15);u.goal=null;}else{go(u,shop,'Buying potions');return;}}}
    let best=null,bestScore=.045;for(const f of G.flags){if(f.dead||f.target?.dead)continue;const threat=f.target?Math.max(.8,(f.target.data.damage||14)/14+(f.target.hp/500)):1;const affinity=f.type==='explore'?(u.type==='ranger'?2.5:.55):u.data.affinity;const score=f.reward/(30*threat)*affinity*u.bravery*(1+(u.level-1)*.18)*(u.hp/u.maxHp)/(1+G.dist(u,f)*.08);if(score>bestScore){best=f;bestScore=score;}}
    if(best){u.goal=best;if(best.type==='attack'){u.target=best.target;u.state='Answering a bounty';}else if(G.dist(u,best)<1.9){best.dead=true;u.gold+=best.reward;u.xp+=20;G.reveal(best.x,best.y,9);G.notify(u.name+' claimed an exploration bounty.');G.fxAt(u.x,u.y,'level');u.goal=null;}else go(u,best,'Exploring for gold');return;}
    u.goal=null;u.target=null;const lair=nearest(u,G.buildings.filter(b=>!b.dead&&b.hostile&&G.dist(u,b)<5));if(lair&&u.hp>u.maxHp*.8&&(u.level>1||u.type==='warrior')){u.target=lair;u.state='Raiding a lair';return;}
    if(u.type==='ranger'){if(!u.path.length){const unexplored=G.tiles.filter(t=>!t.explored&&G.walkable(t.x,t.y)&&G.dist(u,t)<16);if(unexplored.length){go(u,G.pick(unexplored),'Exploring the borderlands');return;}}wander(u,G.palace,18);}else wander(u,u.home&&!u.home.dead?u.home:G.palace,7);
  }
  function peasant(u){const repair=nearest(u,G.buildings.filter(b=>!b.dead&&!b.hostile&&(b.progress<1||b.hp<b.maxHp)));if(repair){const enemies=G.units.some(e=>!e.dead&&e.hostile&&G.dist(e,u)<3);if(enemies){go(u,G.palace,'Seeking shelter');return;}if(G.dist(u,repair)<repair.data.size*.7+1.4){u.path=[];u.target=null;if(repair.progress<1){repair.progress=Math.min(1,repair.progress+.8/repair.data.buildTime);repair.hp=Math.max(repair.hp,repair.maxHp*(.2+.8*repair.progress));u.state='Building '+repair.data.name;if(repair.progress===1){G.notify(repair.data.name+' is ready.');G.sound?.play('complete');}}else{repair.hp=Math.min(repair.maxHp,repair.hp+7);u.state='Repairing '+repair.data.name;}}else go(u,repair,repair.progress<1?'Off to build':'Off to repair');}else wander(u,G.palace,6);}
  function collector(u){if(u.carried>0){if(G.dist(u,G.palace)<3){G.gold+=u.carried;G.stats.taxes+=u.carried;G.lastTax=u.carried;G.fxAt(u.x,u.y,'gold',u.carried);u.carried=0;u.path=[];}else{go(u,G.palace,'Delivering '+Math.floor(u.carried)+' gold');return;}}const shop=nearest(u,G.buildings.filter(b=>!b.dead&&!b.hostile&&b.taxPool>=10));if(shop){if(G.dist(u,shop)<shop.data.size*.7+1.1){u.carried+=Math.floor(shop.taxPool);shop.taxPool-=Math.floor(shop.taxPool);u.path=[];}else go(u,shop,'Collecting taxes');}else wander(u,G.palace,4);}
  function guard(u){const enemy=nearest(u,G.units.filter(e=>!e.dead&&e.hostile&&G.dist(e,G.palace)<11));if(enemy){u.target=enemy;u.state='Defending the kingdom';}else{u.target=null;wander(u,G.palace,5);}}
  function monster(u){let enemy=nearest(u,G.units.filter(e=>!e.dead&&!e.hostile&&G.dist(u,e)<u.data.sight));if(enemy){u.target=enemy;u.state='Attacking';return;}const near=nearest(u,G.buildings.filter(b=>!b.dead&&!b.hostile&&G.dist(u,b)<6));if(near){u.target=near;u.state='Raiding the kingdom';return;}if(G.time>100&&(u.raider||u.type==='troll'||u.home?.dead)){u.target=G.palace;u.state='Marching on the Palace';}else{u.target=null;wander(u,u.home||u,4);}}
  G.thinkUnit=function(u){if(u.hostile)monster(u);else if(u.hero)hero(u);else if(u.type==='peasant')peasant(u);else if(u.type==='collector')collector(u);else guard(u);};
})();
