(function(){
  let nextId=1;
  G.addBuilding=function(type,x,y,built=true){const d=G.BUILDINGS[type],b={id:nextId++,kind:'building',type,data:d,x:x+d.size/2,y:y+d.size/2,tx:x,ty:y,hp:built?d.hp:d.hp*.2,maxHp:d.hp,hostile:!!d.hostile,dead:false,progress:built?1:0,taxPool:0,spawnTimer:d.interval?d.interval+G.random()*12:0,attackTimer:0,lastHit:-100,reinforced:false};G.buildings.push(b);for(let yy=y;yy<y+d.size;yy++)for(let xx=x;xx<x+d.size;xx++){const t=G.tile(xx,yy);if(t)t.blocked=true;}G.trees=G.trees.filter(t=>!(t.x>=x&&t.x<x+d.size&&t.y>=y&&t.y<y+d.size));if(type==='palace')G.palace=b;return b;};
  G.addUnit=function(type,x,y,home){const d=G.UNITS[type],u={id:nextId++,kind:'unit',type,data:d,x,y,hp:d.hp,maxHp:d.hp,hostile:!!d.hostile,hero:!!d.hero,dead:false,home:home||G.palace,level:1,xp:0,gold:0,potions:{healing:0,strength:0,stoneskin:0},buffs:{strength:0,stoneskin:0},carried:0,path:[],goal:null,target:null,think:0,attackTimer:0,attacking:0,lastHit:-100,anim:G.random()*4,facing:1,state:d.hero?'Seeking adventure':'On duty',bravery:d.bravery||1,name:d.hero?G.pick(G.NAMES[type]):d.name,stuck:0};if(home?.infestation)u.infestation=true;G.units.push(u);return u;};
  G.nearPoint=function(x,y,r=2){for(let i=0;i<40;i++){let a=G.random()*Math.PI*2,rr=.6+G.random()*r,xx=x+Math.cos(a)*rr,yy=y+Math.sin(a)*rr;if(G.walkable(xx,yy))return{x:xx,y:yy};}for(let yy=Math.floor(y)-5;yy<y+6;yy++)for(let xx=Math.floor(x)-5;xx<x+6;xx++)if(G.walkable(xx,yy))return{x:xx+.5,y:yy+.5};return{x,y};};
  G.moveTo=function(u,x,y){if(!Number.isFinite(x)||!Number.isFinite(y))return;u.path=G.findPath(u.x,u.y,x,y);u.destination={x,y};u.repath=1.6;};
  G.moveUnit=function(u,dt){if(!u.path.length)return;let amount=u.data.speed*(u.state==='Fleeing'?1.25:1)*dt;while(amount>0&&u.path.length){const p=u.path[0],dx=p.x-u.x,dy=p.y-u.y,d=Math.hypot(dx,dy);if(!G.walkable(p.x,p.y)){u.path=[];u.think=0;break;}if(d<=amount){u.x=p.x;u.y=p.y;amount-=d;u.path.shift();}else{u.x+=dx/d*amount;u.y+=dy/d*amount;amount=0;}if(Math.abs(dx-dy)>.02)u.facing=dx-dy>0?1:-1;u.anim+=dt*7;}u.x=G.clamp(u.x,.1,G.MAP-.1);u.y=G.clamp(u.y,.1,G.MAP-.1);};
  G.damage=function(target,amount,attacker){if(!target||target.dead)return;const armor=target.kind==='unit'?G.unitArmor(target):0;const damage=Math.max(1,amount-armor);target.hp-=damage;target.lastHit=G.time;G.fxAt(target.x,target.y,'hit',damage);if(target.kind==='building'&&target.hostile&&!target.reinforced){target.reinforced=true;target.spawnTimer=Math.min(target.spawnTimer,4);}if(target.hp<=0)G.kill(target,attacker);};
  G.kill=function(e,killer){if(e.dead)return;e.dead=true;e.hp=0;G.stats[e.hostile?'slain':'losses']++;G.fxAt(e.x,e.y,e.kind==='building'?'collapse':'death');
    if(e.kind==='building'){for(let y=e.ty;y<e.ty+e.data.size;y++)for(let x=e.tx;x<e.tx+e.data.size;x++){const t=G.tile(x,y);if(t)t.blocked=false;}G.ruins.push({x:e.x,y:e.y,size:e.data.size});if(e.infestation){G.stats.infestationsCleared++;G.sanitation.timer=0;G.notify('Rat sewer cleared. It can return while the town remains overcrowded.');}else if(e.hostile){G.gold+=e.data.reward;G.notify((e.siteName||e.data.name)+' destroyed. +'+e.data.reward+' crown reward; treasure awaits your heroes.');G.sound?.play('victory');G.stats.lairs++;}else if(e.demolished)G.notify('Cottage dismantled. Construction costs and stored taxes are forfeited.');else G.notify(e.data.name+' has fallen!','danger');}
    if(e.hostile)G.dropLoot(e);
    if(killer?.hero&&!killer.dead&&e.hostile&&!e.infestation){killer.xp+=e.data.xp||60;while(killer.xp>=killer.level*45){killer.xp-=killer.level*45;killer.level++;killer.maxHp+=22;killer.hp=Math.min(killer.maxHp,killer.hp+60);G.fxAt(killer.x,killer.y,'level');G.notify(killer.name+' reached level '+killer.level+'.');G.sound?.play('level');}}
    if(e.type==='collector'&&e.carried)G.notify('A tax collector was lost with '+e.carried+' gold.','danger');
    if(e.hero)G.notify(e.name+' has fallen.','danger');
    for(const f of G.flags)if(!f.dead&&f.target===e){f.dead=true;const candidates=G.units.filter(u=>u.hero&&!u.dead&&G.dist(u,e)<12);if(candidates.length){const share=f.reward/candidates.length;candidates.forEach(u=>u.gold+=share);}else G.gold+=f.reward;G.stats.bounties++;}
  };
  G.attack=function(u,target,dt){if(!target||target.dead)return false;const range=u.data.range+(target.kind==='building'?target.data.size*.45:0);const dist=G.dist(u,target);if(dist>range){if(!u.path.length||u.repath<=0){G.moveTo(u,target.x,target.y);u.repath=1.3;}return false;}G.useCombatPotions(u,target);u.path=[];u.facing=(target.x-u.x)-(target.y-u.y)>0?1:-1;if(u.attackTimer<=0){u.attackTimer=u.data.rate;u.attacking=.34;const amount=G.unitDamage(u,target);if(u.data.range>2){G.projectiles.push({x:u.x,y:u.y,target,attacker:u,damage:amount,type:u.type==='wizard'?'fireball':'arrow',speed:u.type==='wizard'?11:19,life:2});G.sound?.play(u.type==='wizard'?'fire':'bow',.2);}else{G.damage(target,amount,u);if(G.isVisible(u.x,u.y))G.sound?.play('hit',.15);}}return true;};
  G.updateEntities=function(dt){
    for(const u of G.units){if(u.dead)continue;G.updateSupplies(u,dt);if(u.data.regeneration&&G.time-u.lastHit>6)u.hp=Math.min(u.maxHp,u.hp+u.data.regeneration*dt);u.attackTimer-=dt;u.attacking=Math.max(0,u.attacking-dt);u.repath=(u.repath||0)-dt;u.think-=dt;if(u.think<=0){G.thinkUnit(u);u.think=.55+G.random()*.35;}if(u.target&&!u.target.dead&&u.state!=='Fleeing'&&u.state!=='Resting')G.attack(u,u.target,dt);G.moveUnit(u,dt);if(!u.hostile&&G.time-u.lastHit>8&&G.dist(u,G.palace)<7)u.hp=Math.min(u.maxHp,u.hp+dt*(u.hero?2.2:3));}
    for(const p of G.projectiles){if(p.dead)continue;p.life-=dt;if(p.target.dead||p.life<=0){p.dead=true;continue;}const d=G.dist(p,p.target),step=p.speed*dt;if(d<step+.3){G.damage(p.target,p.damage,p.attacker);if(p.type==='fireball'){G.fxAt(p.target.x,p.target.y,'fire');for(const enemy of G.units)if(!enemy.dead&&enemy.hostile!==p.attacker.hostile&&enemy!==p.target&&G.dist(enemy,p.target)<1.6)G.damage(enemy,p.damage*.35,p.attacker);}p.dead=true;}else{p.x+=(p.target.x-p.x)/d*step;p.y+=(p.target.y-p.y)/d*step;}}
    G.projectiles=G.projectiles.filter(p=>!p.dead);
    for(const b of G.buildings){if(b.dead||b.progress<1)continue;if(b.type==='tower'){b.attackTimer-=dt;const t=G.units.filter(u=>!u.dead&&u.hostile&&G.dist(u,b)<b.data.range).sort((a,c)=>G.dist(a,b)-G.dist(c,b))[0];if(t&&b.attackTimer<=0){b.attackTimer=b.data.attackRate;G.projectiles.push({x:b.x,y:b.y,target:t,attacker:b,damage:b.data.damage,type:'arrow',speed:19,life:2});}}}
  };
})();
