(function(){
  G.notify=function(message,kind){if(G.ui)G.ui.notify(message,kind);};
  G.fxAt=function(x,y,type,value){if(G.headless)return;G.effects.push({x,y,type,value,time:0,life:type==='collapse'?2:type==='level'?1.8:1.1,seed:G.random()});};
  G.reset=function(seed=G.seedOverride){G.seed=G.normalizeSeed(seed)??G.newSeed();G.random=G.rng(G.seed);G.units=[];G.buildings=[];G.flags=[];G.projectiles=[];G.effects=[];G.ruins=[];G.time=0;G.gold=1500;G.speed=1;G.paused=false;G.result=null;G.stats={slain:0,losses:0,lairs:0,taxes:0,bounties:0,recruited:0,potionsBought:0,potionsUsed:0};G.cooldowns={heal:0,lightning:0,farsight:0};G.alchemy={unlocked:{},project:null};G.lastTax=0;G.economyTimer=0;G.visionTimer=0;G.trollSpawned=false;G.staffTimer=0;G.mode=null;G.selected=null;G.generateWorld();
    G.addBuilding('palace',19,19);G.addBuilding('house',17,23);G.addBuilding('house',23,19);G.addBuilding('house',23,24);
    for(const site of G.LEVEL.lairs){const b=G.addBuilding(site.type,site.x,site.y);b.siteName=site.name;b.dormant=!!site.frontier;for(let i=0;i<2;i++){const p=G.nearPoint(b.x,b.y,3);G.addUnit(b.data.spawn,p.x,p.y,b);}}
    for(let i=0;i<3;i++){const p=G.nearPoint(20,23,3);G.addUnit('peasant',p.x,p.y,G.palace);}for(let i=0;i<2;i++){const p=G.nearPoint(22,22,3);G.addUnit('guard',p.x,p.y,G.palace);}const p=G.nearPoint(21,23,2);G.addUnit('collector',p.x,p.y,G.palace);G.selected=G.palace;G.updateVision();
  };
  G.build=function(type,x,y){const d=G.BUILDINGS[type];if(G.result||!d||!G.canPlace(type,x,y)){G.notify('Choose clear, explored ground near your kingdom.');return false;}if(G.gold<d.cost){G.notify('Your treasury needs '+(d.cost-Math.floor(G.gold))+' more gold.');return false;}G.gold-=d.cost;const b=G.addBuilding(type,x,y,false);G.selected=b;G.units.filter(u=>u.type==='peasant').forEach(u=>u.think=0);G.notify('Construction ordered: '+d.name+'.');G.sound?.play('build');return b;};
  G.recruit=function(type,guild){const d=G.UNITS[type];if(G.result||!d?.hero)return false;guild=guild||G.buildings.find(b=>!b.dead&&b.progress===1&&b.data.recruits===type&&G.units.filter(u=>!u.dead&&u.home===b&&u.hero).length<b.data.capacity);if(!guild||guild.dead||guild.progress<1||guild.data.recruits!==type){G.notify('Build a '+Object.values(G.BUILDINGS).find(b=>b.recruits===type).name+' first.');return false;}if(G.units.filter(u=>!u.dead&&u.home===guild&&u.hero).length>=guild.data.capacity){G.notify('This guild is full. Build another to recruit more heroes.');return false;}if(G.gold<d.cost){G.notify('Not enough gold to recruit this hero.');return false;}G.gold-=d.cost;const p=G.nearPoint(guild.x,guild.y,2.5),u=G.addUnit(type,p.x,p.y,guild);u.gold=24;G.stats.recruited++;G.notify(u.name+' has joined your kingdom.');G.fxAt(u.x,u.y,'level');G.sound?.play('recruit');return u;};
  G.placeFlag=function(type,x,y,target,reward=100){if(!G.inBounds(x,y)){G.notify('Choose a location within the borderlands.');return false;}if(type==='explore'&&!G.walkable(x,y)){G.notify('Choose open ground for an exploration bounty.');return false;}if(type==='attack'&&(!target||!target.hostile||target.dead)){G.notify('Place an attack bounty on a monster or lair.');return false;}if(type==='attack'&&G.flags.some(f=>!f.dead&&f.target===target)){G.selected=G.flags.find(f=>!f.dead&&f.target===target);G.notify('Select this flag to raise its reward.');return false;}if(G.gold<reward){G.notify('Not enough gold for that bounty.');return false;}G.gold-=reward;const f={id:'flag-'+G.time+'-'+G.random(),kind:'flag',type,x:target?target.x:x,y:target?target.y:y,target,reward,dead:false};G.flags.push(f);G.selected=f;G.units.filter(u=>u.hero).forEach(u=>u.think=0);G.notify((type==='attack'?'Attack':'Exploration')+' bounty posted: '+reward+' gold.');G.sound?.play('flag');return f;};
  G.raiseFlag=function(f,amount=50){if(f.dead||G.gold<amount)return false;f.reward+=amount;G.gold-=amount;G.sound?.play('coin');return true;};
  G.cancelFlag=function(f){if(f.dead)return;G.gold+=f.reward;f.dead=true;G.selected=null;G.notify('Bounty withdrawn. Gold returned to the treasury.');};
  G.spellAvailable=function(type){const d=G.SPELLS[type];return !!d&&(!d.requires||G.buildings.some(b=>b.type===d.requires&&!b.dead&&b.progress===1));};
  G.cast=function(type,x,y){const d=G.SPELLS[type];if(!G.inBounds(x,y)){G.notify('Choose a location within the borderlands.');return false;}if(!G.spellAvailable(type)){G.notify('Build the required guild or temple first.');return false;}if(G.cooldowns[type]>0){G.notify('This spell is still recharging.');return false;}if(G.gold<d.cost){G.notify('Not enough gold for this spell.');return false;}G.gold-=d.cost;G.cooldowns[type]=d.cooldown;
    if(type==='heal'){for(const e of [...G.units,...G.buildings])if(!e.dead&&!e.hostile&&Math.hypot(e.x-x,e.y-y)<4){e.hp=Math.min(e.maxHp,e.hp+130);G.fxAt(e.x,e.y,'heal');}G.fxAt(x,y,'blessing');}
    if(type==='lightning'){const enemies=[...G.units,...G.buildings].filter(e=>!e.dead&&e.hostile&&Math.hypot(e.x-x,e.y-y)<4).sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y));enemies.forEach((e,i)=>G.damage(e,i?65:190,null));G.fxAt(x,y,'lightning');}
    if(type==='farsight'){G.vision.push({x,y,r:10,until:G.time+45});G.reveal(x,y,10);G.fxAt(x,y,'farsight');}G.sound?.play('spell');return true;
  };
  G.update=function(dt){if(G.paused||G.result)return;G.time+=dt;for(const k of Object.keys(G.cooldowns))G.cooldowns[k]=Math.max(0,G.cooldowns[k]-dt);G.updateAlchemy(dt);G.updateEntities(dt);
    for(const b of G.buildings){if(b.dead||!b.hostile)continue;if(b.dormant){if(!G.isExplored(b.x,b.y)&&b.hp===b.maxHp)continue;b.dormant=false;b.spawnTimer=b.data.interval;G.notify(b.siteName+' stirs in the frontier.','danger');}b.spawnTimer-=dt;if(b.spawnTimer<=0){b.spawnTimer=b.data.interval*Math.max(.65,1-G.time/2400);const brood=G.units.filter(u=>!u.dead&&u.hostile&&u.home===b);if(brood.length<6){const p=G.nearPoint(b.x,b.y,2.7),u=G.addUnit(b.data.spawn,p.x,p.y,b);u.raider=G.time>110&&G.random()<.72;}}}
    G.economyTimer+=dt;if(G.economyTimer>=10){G.economyTimer-=10;for(const b of G.buildings)if(!b.dead&&!b.hostile&&b.progress===1){if(b.type==='palace'){G.gold+=b.data.tax;G.stats.taxes+=b.data.tax;}else b.taxPool+=b.data.tax||0;}}
    G.staffTimer+=dt;if(G.staffTimer>40){G.staffTimer=0;for(const type of ['peasant','collector','guard']){const count=G.units.filter(u=>!u.dead&&u.type===type).length;if(count<(type==='peasant'?3:type==='guard'?2:1)&&!G.palace.dead){const p=G.nearPoint(G.palace.x,G.palace.y,4);G.addUnit(type,p.x,p.y,G.palace);}}}
    if(G.time>=600&&!G.trollSpawned){G.trollSpawned=true;const p=G.nearPoint(21,4,3);G.addUnit('troll',p.x,p.y,null);G.notify('A Hill Troll approaches from the north!','danger');G.sound?.play('danger');}
    G.visionTimer+=dt;if(G.visionTimer>=.6){G.visionTimer=0;G.updateVision();}
    if(G.palace.dead){G.result='defeat';G.onEnd?.('defeat');}else if(G.buildings.filter(b=>b.hostile&&!b.dead).length===0){G.result='victory';G.onEnd?.('victory');}
    if(G.units.length>160)G.units=G.units.filter(u=>!u.dead);
  };
})();
