(function(){
  G.keys={};let drag=null,overWorld=false;
  G.hitTest=function(sx,sy){let result=null,best=Infinity;for(const f of G.flags){if(f.dead)continue;const p=G.worldToScreen(f.x,f.y);if(Math.abs(sx-p.x-6)<23*G.camera.zoom&&sy<p.y&&sy>p.y-60*G.camera.zoom)return f;}for(const u of G.units){if(u.dead||u.hostile&&!G.isVisible(u.x,u.y))continue;const p=G.worldToScreen(u.x,u.y),layout=G.unitSpriteLayout(u),z=G.camera.zoom,d=Math.hypot(sx-(p.x+layout.selection[0]*u.facing*z),sy-(p.y+layout.selection[1]*z));if(d<layout.selectionRadius*z&&d<best){result=u;best=d;}}if(result)return result;
    for(const b of G.buildings){if(b.dead||b.hostile&&!G.isExplored(b.x,b.y))continue;const p=G.worldToScreen(b.x,b.y),layout=G.buildingSpriteLayout(b.type),sprite=layout.sprite;let bounds=b.type==='palace'?[-85,-168,85,20]:[-62,-120,62,20];if(sprite.assetLoaded)bounds=sprite.bounds.map((v,i)=>v*layout.scale+(i%2?layout.y:layout.x));const z=G.camera.zoom;if(sx>p.x+bounds[0]*z&&sx<p.x+bounds[2]*z&&sy>p.y+bounds[1]*z&&sy<p.y+bounds[3]*z){
        const x=((sx-p.x)/z-layout.x)/layout.scale,y=((sy-p.y)/z-layout.y)/layout.scale;
        if(!G.spriteContainsPoint(sprite,x,y))continue;
        if(!result||b.x+b.y>result.x+result.y)result=b;
      }}return result;
  };
  G.setMode=function(type,key){G.mode=type?{type,key}:null;G.ui?.updateCommands();G.ui?.modeHint();document.getElementById('world').style.cursor=type?'crosshair':'default';};
  G.changeZoom=function(factor,x,y){const vp=G.viewport();x=x??vp.width/2;y=y??vp.height*.46;const before=G.screenToWorld(x,y);G.camera.zoom=G.clamp(G.camera.zoom*factor,.55,2.1);const after=G.screenToWorld(x,y),a=G.iso(before.x,before.y),b=G.iso(after.x,after.y);G.camera.x+=a.x-b.x;G.camera.y+=a.y-b.y;};
  G.initInput=function(){const c=document.getElementById('world');c.addEventListener('contextmenu',e=>e.preventDefault());
    c.addEventListener('pointerdown',e=>{if(G.welcoming||G.modalOpen)return;c.setPointerCapture(e.pointerId);drag={button:e.button,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};if(e.button===2)c.style.cursor='grabbing';});
    c.addEventListener('pointermove',e=>{G.pointer.x=e.clientX;G.pointer.y=e.clientY;G.pointer.world=G.screenToWorld(e.clientX,e.clientY);overWorld=true;if(drag){const dx=e.clientX-drag.lastX,dy=e.clientY-drag.lastY;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5)drag.moved=true;if(drag.button===2||e.pointerType==='touch'&&drag.moved){G.camera.x-=dx/G.camera.zoom;G.camera.y-=dy/G.camera.zoom;}drag.lastX=e.clientX;drag.lastY=e.clientY;}if(!G.mode&&!drag)G.hovered=G.hitTest(e.clientX,e.clientY);});
    c.addEventListener('pointerleave',()=>{overWorld=false;G.hovered=null;});
    c.addEventListener('pointerup',e=>{if(!drag)return;const was=drag;drag=null;c.style.cursor=G.mode?'crosshair':'default';if(was.moved)return;if(e.button===2){G.setMode(null);return;}if(e.button!==0)return;const wp=G.screenToWorld(e.clientX,e.clientY),hit=G.hitTest(e.clientX,e.clientY);if(G.mode){let ok=false;if(G.mode.type==='build')ok=G.build(G.mode.key,Math.floor(wp.x),Math.floor(wp.y));if(G.mode.type==='bounty')ok=G.placeFlag(G.mode.key,wp.x,wp.y,hit?.hostile?hit:null,100);if(G.mode.type==='spell')ok=G.cast(G.mode.key,wp.x,wp.y);if(ok&&!e.shiftKey)G.setMode(null);G.ui.update(true);return;}G.selected=hit;G.sound?.play('select');G.ui.updateInspector(true);});
    c.addEventListener('pointercancel',()=>{drag=null;});
    c.addEventListener('wheel',e=>{e.preventDefault();if(G.welcoming||G.modalOpen)return;G.changeZoom(e.deltaY>0?.91:1.1,e.clientX,e.clientY);G.pointer.world=G.screenToWorld(e.clientX,e.clientY);},{passive:false});
    window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea'))return;if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();if(e.key==='Escape'){if(G.modalOpen)G.ui.closeModal();else if(G.mode)G.setMode(null);else{G.selected=null;G.ui.updateInspector(true);}return;}if(G.welcoming||G.modalOpen)return;G.keys[e.key.toLowerCase()]=true;if(e.repeat)return;if(e.key===' '){G.paused=!G.paused;G.ui.update(true);}if(['1','2','3'].includes(e.key)){G.speed=Number(e.key);G.paused=false;G.ui.update(true);}if(e.key.toLowerCase()==='f')G.centerCamera();});
    window.addEventListener('keyup',e=>G.keys[e.key.toLowerCase()]=false);window.addEventListener('blur',()=>{G.keys={};drag=null;});
    document.getElementById('minimap').addEventListener('pointerdown',e=>G.minimapNavigate(e.clientX,e.clientY));
  };
  G.updateCamera=function(dt){if(G.welcoming||G.modalOpen)return;const k=G.keys,s=440*dt/G.camera.zoom,vp=G.viewport();let dx=(k.d||k.arrowright?1:0)-(k.a||k.arrowleft?1:0),dy=(k.s||k.arrowdown?1:0)-(k.w||k.arrowup?1:0);if(overWorld&&!drag&&G.pointer.x>0){if(G.pointer.x<8)dx--;if(G.pointer.x>vp.width-8)dx++;if(G.pointer.y<90&&G.pointer.y>81)dy--;if(G.pointer.y>vp.height-8)dy++;}G.camera.x=G.clamp(G.camera.x+dx*s,-1100,1100);G.camera.y=G.clamp(G.camera.y+dy*s,80,1320);if(dx||dy)G.pointer.world=G.screenToWorld(G.pointer.x,G.pointer.y);};
})();
