(function(){
  G.camera={x:0,y:650,zoom:1.12};G.pointer={x:0,y:0,world:{x:0,y:0}};G.renderTime=0;
  let canvas,ctx,terrain,terrainOrigin,fog,fogTime=-1,mini,miniCtx,width=0,height=0,dpr=1;
  const {poly,ellipse,line,grad}=G.art;
  const palette=['#829567','#849769','#85976a','#829568','#86986a','#839669','#86986b'];
  G.screenToWorld=function(x,y){return G.uniso((x-width/2)/G.camera.zoom+G.camera.x,(y-height*.46)/G.camera.zoom+G.camera.y);};
  G.worldToScreen=function(x,y){const p=G.iso(x,y);return{x:(p.x-G.camera.x)*G.camera.zoom+width/2,y:(p.y-G.camera.y)*G.camera.zoom+height*.46};};
  G.clampCamera=function(){const p=G.uniso(G.camera.x,G.camera.y),c=G.iso(G.clamp(p.x,.5,G.MAP-.5),G.clamp(p.y,.5,G.MAP-.5));G.camera.x=c.x;G.camera.y=c.y;};
  G.centerCamera=function(){const p=G.iso(G.palace.x,G.palace.y);G.camera.x=p.x;G.camera.y=p.y-4;};
  G.resize=function(){width=window.innerWidth;height=window.innerHeight;dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;canvas.style.width=width+'px';canvas.style.height=height+'px';};
  function diamond(c,x,y,fill,w=32.35,h=16.18){poly(c,[[x,y],[x+w,y+h],[x,y+h*2],[x-w,y+h]],fill);}
  G.makeTerrain=function(){terrain={width:G.MAP*G.TW+128,height:G.MAP*G.TH+128};terrainOrigin={x:terrain.width/2,y:35};fogTime=-1;if(G.environment?.ready()){G.environment.prepare();return;}const size=terrain;terrain=document.createElement('canvas');Object.assign(terrain,size);const c=terrain.getContext('2d'),r=G.rng(1832);c.translate(terrainOrigin.x,terrainOrigin.y);
    for(const t of G.tiles){const p=G.iso(t.x,t.y);if(t.kind==='water'){diamond(c,p.x,p.y,['#47766e','#48776f','#49786f','#4a796f'][Math.floor(t.noise*4)]);for(let i=0;i<3;i++){const xx=p.x+(r()-.5)*27,yy=p.y+7+r()*15;line(c,[[xx,yy],[xx+4+r()*9,yy-.5]],'#a9c5a524',.7);}}
      else {diamond(c,p.x,p.y,palette[Math.floor(t.noise*palette.length)]);for(let i=0;i<14;i++){const a=r(),b=r(),xx=p.x+(a-b)*32,yy=p.y+(a+b)*16;ellipse(c,xx,yy,.5+r()*1.5,.35+r()*.65,i%3?'#bfbd7b25':'#455e3b20');if(i<3)line(c,[[xx,yy],[xx+.4,yy-1.9]],'#cad29228',.7);}}
    }
    // Blended shore ribbons: shallow green water, sand, and a fine pale edge.
    for(const t of G.tiles){const p=G.iso(t.x,t.y);if(t.kind==='water'){
      const edges=[[-1,0,[[p.x-32,p.y+16],[p.x,p.y]]],[0,-1,[[p.x,p.y],[p.x+32,p.y+16]]],[1,0,[[p.x+32,p.y+16],[p.x,p.y+32]]],[0,1,[[p.x,p.y+32],[p.x-32,p.y+16]]]];
      for(const[dx,dy,pts]of edges){const n=G.tile(t.x+dx,t.y+dy);if(n&&n.kind!=='water'&&n.kind!=='bridge'){line(c,pts,'#869b7370',11);line(c,pts,'#b3b58a80',5);line(c,pts,'#d3d1a66a',1);}}
    }if(t.kind==='path'){diamond(c,p.x,p.y,'#b3aa80a0');for(let i=0;i<10;i++){const a=r(),b=r();ellipse(c,p.x+(a-b)*28,p.y+(a+b)*14+2,1.4+r()*2,.5+r(),'#d4c39460');}line(c,[[p.x-25,p.y+15],[p.x-3,p.y+3]],'#d4c8933a',2);}
      if(t.kind==='bridge'){diamond(c,p.x,p.y,'#8f835d');for(let i=0;i<8;i++)line(c,[[p.x-32+i*4,p.y+16-i*2],[p.x+i*4,p.y+32-i*2]],i%2?'#b5a178':'#a0926a',2.8);}
    }
    // A cobbled palace court joins the crossing roads.
    for(let y=G.palace.ty-2;y<G.palace.ty+5;y++)for(let x=G.palace.tx-2;x<G.palace.tx+5;x++){if(Math.hypot(x-G.palace.x,y-G.palace.y)>3.6)continue;const p=G.iso(x,y);diamond(c,p.x,p.y,'#b2b29390');for(let i=0;i<12;i++){const a=r(),b=r();ellipse(c,p.x+(a-b)*29,p.y+(a+b)*15,2+r()*2,.8+r(),i%2?'#d1ccb080':'#7e8e7150');}}
    for(const d of G.decor){const p=G.iso(d.x,d.y);if(d.type==='rock'){shadowRock(c,p.x,p.y,d.seed);}else{for(let i=0;i<4;i++){let xx=p.x+(r()-.5)*15,yy=p.y+(r()-.5)*5;line(c,[[xx,yy],[xx,yy-3]],'#617d4f',.7);ellipse(c,xx,yy-3,1.1,.8,d.seed>.5?'#dac98b90':'#c7caa195');}}}
  };
  function shadowRock(c,x,y,s){ellipse(c,x+2,y+2,6+s*5,2+s*2,'#4a664538');poly(c,[[x-5-s*3,y],[x-3,y-4-s*4],[x+3+s*3,y-3],[x+7,y+1],[x+1,y+3]],'#9da58d');poly(c,[[x-5-s*3,y],[x-3,y-4-s*4],[x+1,y-2],[x+1,y+3]],'#b1b49a');}
  function makeFog(){if(!fog)fog=document.createElement('canvas');fog.width=Math.ceil(terrain.width/3);fog.height=Math.ceil(terrain.height/3);const c=fog.getContext('2d');c.fillStyle='#233b3c85';c.fillRect(0,0,fog.width,fog.height);c.scale(1/3,1/3);c.translate(terrainOrigin.x,terrainOrigin.y);c.globalCompositeOperation='destination-out';for(const t of G.tiles){if(t.explored&&!t.visible){const p=G.iso(t.x,t.y);diamond(c,p.x,p.y,'#ffffff55');}}const light=(x,y,r)=>{const p=G.iso(x,y);c.save();c.translate(p.x,p.y);c.scale(1,.5);const g=c.createRadialGradient(0,0,r*34,0,0,r*48);g.addColorStop(0,'#ffffffff');g.addColorStop(1,'#ffffff00');ellipse(c,0,0,r*48,r*48,g);c.restore();};for(const b of G.buildings)if(!b.dead&&!b.hostile)light(b.x,b.y,b.data.sight||5);for(const u of G.units)if(!u.dead&&!u.hostile)light(u.x,u.y,u.data.sight);for(const v of G.vision)light(v.x,v.y,v.r);}
  G.initRender=function(){canvas=document.getElementById('world');ctx=canvas.getContext('2d',{alpha:false});mini=document.getElementById('minimap');miniCtx=mini.getContext('2d');G.resize();G.centerCamera();G.makeTerrain();window.addEventListener('resize',G.resize);};
  function visibleScreen(p,margin=200){return p.x>-margin&&p.x<width+margin&&p.y>-margin&&p.y<height+margin;}
  function groundRing(e,color){const p=G.iso(e.x,e.y);ctx.save();ctx.strokeStyle=color;ctx.lineWidth=1/G.camera.zoom;ctx.setLineDash([4,3]);ctx.beginPath();ctx.ellipse(p.x,p.y+7,e.kind==='building'?e.data.size*24:15,e.kind==='building'?e.data.size*12:7.5,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.restore();}
  function hpBar(e,p){if(e.dead)return;const building=e.kind==='building',layout=building?G.buildingSpriteLayout(e.type):null,w=building?52:25,y=p.y+(layout?.sprite.assetLoaded?layout.y+layout.sprite.bounds[1]*layout.scale-9:building?-104:G.unitSpriteLayout(e).healthOffset);ctx.fillStyle='#17372bca';ctx.fillRect(p.x-w/2-1,y-1,w+2,5);ctx.fillStyle=e.hostile?'#b8785d':'#d0c987';ctx.fillRect(p.x-w/2,y,w*G.clamp(e.hp/e.maxHp,0,1),3);}
  function drawBuilding(b){const p=G.iso(b.x,b.y);if(b===G.selected||b===G.hovered)groundRing(b,b===G.selected?'#edd69c':'#f0e5c478');const layout=G.buildingSpriteLayout(b.type),sprite=layout.sprite;ctx.save();if(b.progress<1)ctx.globalAlpha=.38+b.progress*.52;ctx.imageSmoothingEnabled=!sprite.pixelArt;ctx.imageSmoothingQuality='high';ctx.drawImage(sprite.canvas,p.x+layout.x,p.y+layout.y,layout.w,layout.h);ctx.restore();
    if(b.progress<1){const w=b.data.size*25;for(let i=-1;i<=1;i++){const xx=p.x+i*w*.65;line(ctx,[[xx,p.y+10],[xx,p.y-65]],'#978258',2.1);line(ctx,[[xx-4,p.y-64],[xx+4,p.y-67]],'#c2a97a',1.2);}line(ctx,[[p.x-w,p.y-25],[p.x+w,p.y-25]],'#ad9464',2);line(ctx,[[p.x-w,p.y-50],[p.x+w,p.y-50]],'#ad9464',2);line(ctx,[[p.x-w*.65,p.y+5],[p.x+w*.65,p.y-50]],'#b5a275',1.4);ctx.fillStyle='#183a29';ctx.fillRect(p.x-24,p.y-84,48,4);ctx.fillStyle='#d9b775';ctx.fillRect(p.x-24,p.y-84,48*b.progress,4);}
    if(b===G.selected||b===G.hovered||G.time-b.lastHit<4)hpBar(b,p);
    if(!sprite.assetLoaded&&['palace','house','warriors'].includes(b.type)){const sx=p.x+(b.type==='palace'?17:-15),sy=p.y-(b.type==='palace'?117:83);for(let i=0;i<3;i++){const t=(G.renderTime*.14+i*.33+b.id*.11)%1;ellipse(ctx,sx+Math.sin(t*7+b.id)*6,sy-t*38,3+t*8,2+t*5,'rgba(215,218,187,'+(1-t)*.12+')');}}
    if(b.type==='goblin'&&!sprite.assetLoaded){const pulse=Math.sin(G.renderTime*10+b.id)*.2+.8;ellipse(ctx,p.x-30,p.y+1,5*pulse,6,'#ebad6260');ellipse(ctx,p.x-30,p.y-2,2.5,4*pulse,'#e7c17cb0');}
    for(const effect of sprite.effects||[]){
      const ex=p.x+layout.x+effect.at[0]*layout.scale,ey=p.y+layout.y+effect.at[1]*layout.scale;
      if(effect.type==='smoke')for(let i=0;i<3;i++){const t=(G.renderTime*.14+i*.33+b.id*.11)%1;ellipse(ctx,ex+Math.sin(t*7+b.id)*5,ey-t*31,2+t*7,2+t*4,'rgba(215,218,187,'+(1-t)*.13+')');}
      if(effect.type==='fire'){const pulse=Math.sin(G.renderTime*10+b.id)*.2+.8;ellipse(ctx,ex,ey,5*pulse,6,'#ebad6240');ellipse(ctx,ex,ey-2,2,3*pulse,'#e7c17c80');}
    }
    if(b.type==='palace'&&!sprite.assetLoaded){const yy=p.y-189;poly(ctx,[[p.x-7,yy],[p.x+6,yy+1+Math.sin(G.renderTime*3)*1.5],[p.x+8,yy+8+Math.sin(G.renderTime*3+1)*1.5],[p.x-7,yy+8]],'#d6bf89');}
  }
  function drawUnit(u){const p=G.iso(u.x,u.y);if(u===G.selected||u===G.hovered)groundRing(u,u.hostile?'#db9b72':'#f1d7a1');const layout=G.unitSpriteLayout(u),sprite=layout.sprite;ctx.save();ctx.translate(p.x,p.y);ctx.scale(u.facing,1);ctx.imageSmoothingEnabled=!sprite.pixelArt;ctx.imageSmoothingQuality='high';G.paintSprite(ctx,sprite,layout.x,layout.y,layout.w,layout.h);ctx.restore();if(u===G.selected||u===G.hovered||G.time-u.lastHit<3)hpBar(u,p);if(u.hero&&u.level>1){ctx.fillStyle='#e0ca86';ctx.font='8px Alegreya, Georgia, serif';ctx.textAlign='center';ctx.fillText('✦ '+u.level,p.x,p.y+layout.healthOffset-4);}if(u.type==='collector'&&u.carried>0){ellipse(ctx,p.x+7,p.y-17,2,2,'#e2bf66');}}
  function drawLoot(loot){
    const p=G.iso(loot.x,loot.y),s=G.sprites[loot.type];
    if(loot===G.selected||loot===G.hovered)groundRing(loot,'#edce85');
    G.paintSprite(ctx,s,p.x-s.anchor[0],p.y-s.anchor[1],s.w,s.h);
    let i=0;for(const [key,n]of Object.entries(loot.potions)){if(!n)continue;const x=p.x+14+i++*5,y=p.y-7;
      ellipse(ctx,x,y+5,3,1.5,'#19342b55');ctx.fillStyle='#b4c4b5';ctx.fillRect(x-1,y-7,2,4);
      ellipse(ctx,x,y,2.7,4,({healing:'#a84a40',strength:'#bd8b42',stoneskin:'#638c9b'})[key]);line(ctx,[[x-1,y-3],[x-1,y+1]],'#f4e9baaa',.7);ctx.fillStyle='#8f7350';ctx.fillRect(x-1.5,y-8,3,1.5);
    }
    const glow=.4+.3*Math.sin(G.renderTime*2+loot.x);line(ctx,[[p.x-4,p.y-17],[p.x+4,p.y-17]],'rgba(249,222,147,'+glow+')',.8);line(ctx,[[p.x,p.y-21],[p.x,p.y-13]],'rgba(249,222,147,'+glow+')',.8);
  }
  function drawEffects(dt){G.effects=G.effects.filter(e=>e.time<e.life);for(const e of G.effects){e.time+=dt;const t=e.time/e.life,p=G.iso(e.x,e.y),alpha=1-t;ctx.save();ctx.globalAlpha=alpha;if(e.type==='lightning'){line(ctx,[[p.x-12,p.y-170],[p.x+12,p.y-105],[p.x-7,p.y-95],[p.x+7,p.y-35],[p.x,p.y]],'#f4edd0',3);line(ctx,[[p.x-12,p.y-170],[p.x+12,p.y-105],[p.x-7,p.y-95],[p.x+7,p.y-35],[p.x,p.y]],'#9dbdc9',7);ellipse(ctx,p.x,p.y,28*t,14*t,'#e1e0c845');}else if(['heal','level','blessing','farsight'].includes(e.type)){ctx.strokeStyle=e.type==='heal'?'#b3dba2':'#e3cd8b';ctx.lineWidth=1.8;ctx.beginPath();ctx.ellipse(p.x,p.y,12+t*40,6+t*20,0,0,Math.PI*2);ctx.stroke();for(let i=0;i<8;i++){const a=i*.785+e.seed;ellipse(ctx,p.x+Math.cos(a)*(8+t*15),p.y-t*40+Math.sin(a)*5,1.2,2.5,'#e6d89d');}}else if(e.type==='gold'){ctx.fillStyle='#f5df9d';ctx.font='bold 12px Alegreya, Georgia, serif';ctx.textAlign='center';ctx.fillText('+'+Math.floor(e.value),p.x,p.y-25-t*25);}else{const r=G.rng(Math.floor(e.seed*9999));for(let i=0;i<(e.type==='collapse'?24:7);i++){const a=r()*Math.PI*2,s=(e.type==='collapse'?42:16)*r();ellipse(ctx,p.x+Math.cos(a)*s*t,p.y-12+Math.sin(a)*s*t-t*15,1+r()*2,1+r()*2,e.type==='fire'?'#e7b876':e.type==='collapse'?'#bdc3a2':'#d0bc8c');}if(e.value&&e.type==='hit'){ctx.fillStyle='#e9d1a1';ctx.font='9px Alegreya, Georgia, serif';ctx.textAlign='center';ctx.fillText(Math.ceil(e.value),p.x,p.y-30-t*17);}}ctx.restore();}}
  G.render=function(dt){if(!ctx)return;G.renderTime+=dt;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#263e33';ctx.fillRect(0,0,width,height);ctx.save();ctx.translate(width/2-G.camera.x*G.camera.zoom,height*.46-G.camera.y*G.camera.zoom);ctx.scale(G.camera.zoom,G.camera.zoom);const landscape=G.environment?.ready(),groundView={x:G.camera.x-width/2/G.camera.zoom,y:G.camera.y-height*.46/G.camera.zoom,w:width/G.camera.zoom,h:height/G.camera.zoom};if(landscape){G.environment.drawGround(ctx,groundView,G.camera.zoom*dpr);G.environment.drawWater(ctx,groundView,G.renderTime);}else ctx.drawImage(terrain,-terrainOrigin.x,-terrainOrigin.y);
    if(!landscape)for(const t of G.tiles){if(t.kind==='water'){const p=G.iso(t.x,t.y);if(!visibleScreen(G.worldToScreen(t.x,t.y),40))continue;const wave=Math.sin(G.renderTime*1.1+t.x*.9+t.y*.7);if(wave>.55)line(ctx,[[p.x-9+wave*7,p.y+15],[p.x+6+wave*7,p.y+15]],'#d3d9b91f',1);}}
    for(const ruin of G.ruins){const p=G.iso(ruin.x,ruin.y);ellipse(ctx,p.x,p.y,28,15,'#586b4d50');for(let i=0;i<8;i++){const rock=G.environment?.layout('rock'+i%4,.42+i%3*.12);if(rock)G.paintSprite(ctx,rock.sprite,p.x+Math.sin(i*9)*25+rock.x,p.y+Math.cos(i*7)*12+rock.y,rock.w,rock.h);else shadowRock(ctx,p.x+Math.sin(i*9)*25,p.y+Math.cos(i*7)*12,i/8);}}
    const scene=[];for(const loot of G.loot)if(!loot.dead&&G.isVisible(loot.x,loot.y)&&visibleScreen(G.worldToScreen(loot.x,loot.y),60))scene.push({z:loot.x+loot.y-.1,loot});if(landscape)for(const prop of [...G.environment.decor,...G.environment.rails])if(visibleScreen(G.worldToScreen(prop.x,prop.y),80))scene.push({z:prop.x+prop.y+.015,prop});for(const tree of G.trees)if(visibleScreen(G.worldToScreen(tree.x,tree.y)))scene.push({z:tree.x+tree.y,tree});for(const b of G.buildings)if(!b.dead&&(!b.hostile||G.isExplored(b.x,b.y))&&visibleScreen(G.worldToScreen(b.x,b.y)))scene.push({z:b.x+b.y+.4,b});for(const u of G.units)if(!u.dead&&(!u.hostile||G.isVisible(u.x,u.y))&&visibleScreen(G.worldToScreen(u.x,u.y),80))scene.push({z:u.x+u.y,u});scene.sort((a,b)=>a.z-b.z);
    for(const o of scene){if(o.loot){drawLoot(o.loot);}else if(o.prop){G.environment.drawProp(ctx,o.prop);}else if(o.tree){const t=o.tree;if(G.environment?.drawTree(ctx,t,G.renderTime))continue;const p=G.iso(t.x,t.y),s=t.scale*.84,sway=Math.sin(G.renderTime*1.15+t.x*.3+t.y*.7)*.6;ctx.drawImage(G.sprites[t.type].canvas,p.x-56*s+sway,p.y-140*s,112*s,156*s);}else if(o.b)drawBuilding(o.b);else drawUnit(o.u);}
    for(const f of G.flags){if(f.dead)continue;if(f.target&&!f.target.dead){f.x=f.target.x;f.y=f.target.y;}const p=G.iso(f.x,f.y),s=G.sprites[f.type==='attack'?'flag':'explore'];ctx.drawImage(s.canvas,p.x-26,p.y-77,64,82);ctx.font='bold 10px Alegreya, Georgia, serif';ctx.textAlign='center';ctx.fillStyle='#172f27';ctx.fillRect(p.x-13,p.y-50,40,14);ctx.fillStyle='#ebd295';ctx.fillText(Math.floor(f.reward)+'g',p.x+7,p.y-40);}
    for(const p of G.projectiles){if(!G.isVisible(p.x,p.y))continue;const a=G.iso(p.x,p.y),b=G.iso(p.target.x,p.target.y);if(p.type==='fireball'){ellipse(ctx,a.x,a.y-18,5,5,'#d7974a70');ellipse(ctx,a.x,a.y-18,2.5,2.5,'#f3d993');}else{const angle=Math.atan2(b.y-a.y,b.x-a.x);line(ctx,[[a.x-Math.cos(angle)*9,a.y-19-Math.sin(angle)*9],[a.x,a.y-19]],'#e1d8b0',1.2);}}
    drawEffects(dt);
    // Low-resolution feathered mist keeps the frontier soft, with visibility still enforced by simulation tiles.
    if(fogTime!==Math.floor(G.time*2)){fogTime=Math.floor(G.time*2);makeFog();}ctx.drawImage(fog,-terrainOrigin.x,-terrainOrigin.y,terrain.width,terrain.height);
    if(G.mode){const wp=G.pointer.world,x=Math.floor(wp.x),y=Math.floor(wp.y);if(G.mode.type==='build'){const type=G.mode.key,d=G.BUILDINGS[type],valid=G.canPlace(type,x,y)&&G.gold>=d.cost;for(let yy=y;yy<y+d.size;yy++)for(let xx=x;xx<x+d.size;xx++){const p=G.iso(xx,yy);diamond(ctx,p.x,p.y,valid?'#d9d1a24d':'#b75e595c');line(ctx,[[p.x,p.y],[p.x+32,p.y+16],[p.x,p.y+32],[p.x-32,p.y+16],[p.x,p.y]],valid?'#e1d798':'#dc8d77',1);}const p=G.iso(x+d.size/2,y+d.size/2),layout=G.buildingSpriteLayout(type);ctx.save();ctx.globalAlpha=.6;ctx.imageSmoothingEnabled=!layout.sprite.pixelArt;ctx.imageSmoothingQuality='high';ctx.drawImage(layout.sprite.canvas,p.x+layout.x,p.y+layout.y,layout.w,layout.h);ctx.restore();}else{const p=G.iso(wp.x,wp.y);ctx.strokeStyle='#ecce8ba0';ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(p.x,p.y,G.mode.type==='spell'?65:20,G.mode.type==='spell'?32:10,0,0,Math.PI*2);ctx.stroke();}}
    ctx.restore();
    // Gentle atmospheric light falls from the upper left.
    const light=ctx.createLinearGradient(0,0,width,height);light.addColorStop(0,'#dce4b60a');light.addColorStop(.5,'#d0c99600');light.addColorStop(1,'#0e2b3422');ctx.fillStyle=light;ctx.fillRect(0,0,width,height);
    if(Math.floor(G.renderTime*8)!==G.lastMini){G.lastMini=Math.floor(G.renderTime*8);G.drawMinimap();}
  };
  G.minimapTransform=()=>({scale:Math.min((mini.width-16)/(2*G.MAP),(mini.height-16)/(2*G.MAP*.66)),ox:mini.width/2,oy:8});
  G.drawMinimap=function(){if(!miniCtx)return;const c=miniCtx,w=mini.width,h=mini.height;c.clearRect(0,0,w,h);c.fillStyle='#1d352c';c.fillRect(0,0,w,h);const {scale,ox,oy}=G.minimapTransform();for(const t of G.tiles){const x=(t.x-t.y)*scale+ox,y=(t.x+t.y)*scale*.66+oy;c.fillStyle=t.explored?(t.kind==='water'?'#558b95':t.kind==='path'?'#b6a579':t.blocked?'#52683c':'#84905b'):(t.kind==='water'?'#385953':'#435e47');c.fillRect(x,y,scale+1,scale*.66+1);}for(const b of G.buildings){if(b.dead)continue;if(b.hostile&&!G.isExplored(b.x,b.y))continue;const x=(b.x-b.y)*scale+ox,y=(b.x+b.y)*scale*.66+oy;c.fillStyle=b.hostile?'#d19273':'#e7cc86';c.fillRect(x-2,y-2,b.type==='palace'?6:4,b.type==='palace'?5:3);}for(const u of G.units)if(!u.dead&&u.hero){c.fillStyle='#e0dba9';c.fillRect((u.x-u.y)*scale+ox,(u.x+u.y)*scale*.66+oy,2,2);}const corners=[[0,81],[width,81],[width,height],[0,height]].map(p=>G.screenToWorld(...p)).map(p=>[(p.x-p.y)*scale+ox,(p.x+p.y)*scale*.66+oy]);line(c,[...corners,corners[0]],'#e3d3a475',.8);c.fillStyle='#d4c18d';c.font='8px Alegreya, Georgia, serif';c.fillText('N',w-15,15);line(c,[[w-13,20],[w-13,31]],'#b7ac7a',.8);};
  G.minimapNavigate=function(clientX,clientY){const rect=mini.getBoundingClientRect(),{scale,ox,oy}=G.minimapTransform(),x=(clientX-rect.left)*mini.width/rect.width-ox,y=(clientY-rect.top)*mini.height/rect.height-oy;const wx=(x/scale+y/(scale*.66))/2,wy=(y/(scale*.66)-x/scale)/2,p=G.iso(wx,wy);G.camera.x=p.x;G.camera.y=p.y;G.clampCamera();};
  G.viewport=()=>({width,height});
})();
