(function(){
  let tab='build',lastInspector='',lastGold=-1,lastSecond=-1,tip=0,wasPaused=false;
  const $=id=>document.getElementById(id),escape=G.escape;
  const buildOrder=['warriors','rangers','wizards','marketplace','temple','tower','house'];
  G.ui={
    init(){
      if(window.innerWidth<=580){document.querySelector('.quest-panel').classList.add('collapsed');$('quest-toggle').innerHTML='Show objectives <span>⌄</span>';}
      document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;G.setMode(null);this.updateCommands();G.sound.play('select');}));
      document.querySelectorAll('[data-speed]').forEach(b=>b.addEventListener('click',()=>{G.speed=Number(b.dataset.speed);G.paused=false;this.update(true);}));
      $('pause').addEventListener('click',()=>{if(G.welcoming)return;G.paused=!G.paused;this.update(true);});
      $('sound').addEventListener('click',()=>{G.sound.toggle();this.update(true);});
      $('help').addEventListener('click',()=>this.showHelp());$('start').addEventListener('click',()=>G.start());
      $('center').addEventListener('click',()=>G.centerCamera());$('zoom-in').addEventListener('click',()=>G.changeZoom(1.16));$('zoom-out').addEventListener('click',()=>G.changeZoom(.86));
      $('quest-toggle').addEventListener('click',()=>{const panel=document.querySelector('.quest-panel');panel.classList.toggle('collapsed');$('quest-toggle').innerHTML=panel.classList.contains('collapsed')?'Show objectives <span>⌄</span>':'Hide objectives <span>⌃</span>';});
      $('next-tip').addEventListener('click',()=>{tip=(tip+1)%G.TIPS.length;$('advisor-text').textContent=G.TIPS[tip];});
      $('modal').addEventListener('click',e=>{if(e.target===$('modal')&&!G.result)this.closeModal();});
      G.onEnd=result=>this.showEnd(result);this.updateCommands();this.update(true);
    },
    notify(message,kind){const el=document.createElement('div');el.className='notification'+(kind?' '+kind:'');el.textContent=message;$('notifications').appendChild(el);while($('notifications').children.length>4)$('notifications').firstChild.remove();setTimeout(()=>el.classList.add('fade'),4200);setTimeout(()=>el.remove(),4800);},
    thumbnail(canvas,type,unit=false){const c=canvas.getContext('2d');canvas.width=180;canvas.height=100;c.clearRect(0,0,180,100);if(unit){const s=G.sprites['idle_'+type]||G.sprites['unit_'+type][1];if(s.assetLoaded){const b=s.bounds,w=b[2]-b[0],h=b[3]-b[1],scale=Math.min(160/w,90/h);c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';G.paintSprite(c,s,(180-w*scale)/2-b[0]*scale,(100-h*scale)/2-b[1]*scale,s.w*scale,s.h*scale);}else c.drawImage(s.canvas,0,0,s.canvas.width,s.canvas.height,50,-4,84,100);}else{const s=G.sprites[type];if(s.assetLoaded){const b=s.bounds,r=s.canvas.width/s.w,w=b[2]-b[0],h=b[3]-b[1],scale=90/Math.max(w,h);c.imageSmoothingEnabled=!s.pixelArt;c.imageSmoothingQuality='high';c.drawImage(s.canvas,b[0]*r,b[1]*r,w*r,h*r,(180-w*scale)/2,(100-h*scale)/2,w*scale,h*scale);}else c.drawImage(s.canvas,30,25,390,430,39,-3,102,113);}},
    updateCommands(){
      document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const cards=$('command-cards');cards.innerHTML='';
      const add=(key,name,price,desc,options={})=>{const b=document.createElement('button');b.className='command-card';if(G.mode?.key===key)b.classList.add('selected');b.setAttribute('aria-label',name+', '+price+' gold');b.innerHTML=(options.symbol?'<span class="card-symbol">'+options.symbol+'</span>':'<canvas aria-hidden="true"></canvas>')+'<span class="card-name">'+escape(name)+'</span><span class="card-price '+(G.gold<price?'unaffordable':'')+'"><span>✦</span>'+price+'</span>';if(options.locked){b.classList.add('locked');b.querySelector('.card-price').innerHTML='<span>◇</span>'+escape(options.locked);}
        cards.appendChild(b);if(!options.symbol)this.thumbnail(b.querySelector('canvas'),key,options.unit);b.addEventListener('click',()=>{if(options.action)options.action();else G.setMode(G.mode?.key===key?null:tab==='build'?'build':tab==='bounty'?'bounty':'spell',key);G.sound.play('select');$('tooltip').classList.add('hidden');});
        b.addEventListener('mouseenter',()=>{const t=$('tooltip');t.innerHTML='<strong>'+escape(name)+'</strong>'+escape(desc)+(options.locked?'<em>'+escape(options.locked)+'</em>':'');t.classList.remove('hidden');const rect=b.getBoundingClientRect();t.style.left=G.clamp(rect.left,8,window.innerWidth-244)+'px';t.style.top=Math.max(84,rect.top-t.offsetHeight-12)+'px';});b.addEventListener('mouseleave',()=>$('tooltip').classList.add('hidden'));};
      if(tab==='build'){for(const key of buildOrder){const d=G.BUILDINGS[key];add(key,d.short,d.cost,d.description);} $('command-description').textContent='Lay the foundations of a flourishing kingdom.';}
      if(tab==='recruit'){for(const key of ['warrior','ranger','wizard']){const d=G.UNITS[key],guild=G.buildings.find(b=>b.data.recruits===key&&!b.dead&&b.progress===1);add(key,d.name,d.cost,key==='warrior'?'A brave melee fighter. Drawn to high rewards and glorious battles.':key==='ranger'?'A quick archer and eager explorer. Excellent for uncovering the map.':'A powerful fireball caster. Fragile, but formidable behind a warrior.',{unit:true,locked:!guild?'Guild required':null,action:()=>{G.recruit(key);this.update(true);}});} $('command-description').textContent='Offer a place in your kingdom. Their destiny is their own.';}
      if(tab==='bounty'){add('attack','Attack bounty',100,'Place on a monster or lair. Heroes weigh your reward against the danger. Select a placed flag to add more gold.',{symbol:'⚑'});add('explore','Explore bounty',100,'Place on any location. The first hero to reach it claims the reward and reveals nearby terrain.',{symbol:'⚐'});$('command-description').textContent='Heroes follow their own hearts. Gold helps them find the way.';}
      if(tab==='spells'){for(const[key,d]of Object.entries(G.SPELLS))add(key,d.name,d.cost,d.description,{symbol:d.symbol,locked:!G.spellAvailable(key)?G.BUILDINGS[d.requires].short+' required':G.cooldowns[key]>0?Math.ceil(G.cooldowns[key])+'s cooldown':null});$('command-description').textContent='A sovereign’s will can change the course of a battle.';}
    },
    modeHint(){const h=$('mode-hint');if(!G.mode){h.classList.add('hidden');return;}h.classList.remove('hidden');const m=G.mode;h.innerHTML=m.type==='build'?'Place '+escape(G.BUILDINGS[m.key].name)+' <span style="color:#cfb477">· '+G.BUILDINGS[m.key].cost+' gold</span><small>Click clear ground · Shift to build multiple · Esc to cancel</small>':m.type==='bounty'?(m.key==='attack'?'Choose a monster or lair':'Choose a place to explore')+'<small>100 gold reward · Esc to cancel</small>':'Cast '+escape(G.SPELLS[m.key].name)+'<small>Click a location · '+G.SPELLS[m.key].cost+' gold · Esc to cancel</small>';},
    update(force=false){const sec=Math.floor(G.time);if(!force&&sec===lastSecond&&Math.floor(G.gold)===lastGold)return;lastSecond=sec;lastGold=Math.floor(G.gold);$('gold').textContent=Math.floor(G.gold).toLocaleString('en-US');const heroes=G.units.filter(u=>u.hero&&!u.dead),capacity=G.buildings.filter(b=>!b.dead&&b.progress===1).reduce((sum,b)=>sum+(b.data.capacity||0),0);$('hero-count').innerHTML=heroes.length+' <em>/ '+Math.max(12,capacity)+'</em>';$('income').textContent='+'+G.buildings.filter(b=>!b.dead&&b.progress===1).reduce((sum,b)=>sum+(b.data.tax||0),0);$('income').title='Gold produced every 10 seconds; shops and cottages require collection';$('day').textContent='Day '+(1+Math.floor(G.time/120));$('day-phase').textContent=['THE MORNING WATCH','THE AFTERNOON SUN','THE EVENING WATCH'][Math.floor(G.time/40)%3];$('pause').textContent=G.paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',G.paused?'Resume game':'Pause game');$('paused-label').classList.toggle('hidden',!G.paused||G.modalOpen);document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===G.speed));$('sound').classList.toggle('muted',!G.sound.enabled);$('sound').title=G.sound.enabled?'Mute sound':'Enable sound';$('sound').setAttribute('aria-label',$('sound').title);
      const lairs=G.buildings.filter(b=>b.hostile),done=lairs.filter(b=>b.dead).length;$('lair-count').textContent=done+' / 4';$('quest-progress').style.width=done/4*100+'%';$('objectives').innerHTML=lairs.map((b,i)=>'<div class="objective '+(b.dead?'done':'')+'"><span class="box">'+(b.dead?'✓':'')+'</span><span>'+escape(b.type==='goblin'?(i===2?'Western Goblin Camp':'Eastern Goblin Camp'):b.data.name)+'</span></div>').join('');$('palace-condition').style.color=G.palace.hp<G.palace.maxHp*.3?'#d28269':'#8aa875';
      this.updateInspector(force);if(force||tab==='spells')this.updateCommands();else document.querySelectorAll('.card-price').forEach((el,i)=>{if(tab==='build')el.classList.toggle('unaffordable',G.gold<G.BUILDINGS[buildOrder[i]].cost);});
      if(sec>0&&sec%35===0){tip=Math.floor(sec/35)%G.TIPS.length;$('advisor-text').textContent=G.TIPS[tip];}
    },
    updateInspector(force=false){let e=G.selected;if(e?.dead){G.selected=null;e=null;}const panel=$('inspector');panel.classList.toggle('hidden',!e);if(!e){lastInspector='';return;}const key=e.id+':'+(e.kind==='flag'?Math.floor(e.reward):Math.ceil(e.hp))+':'+(e.progress||0).toFixed(2)+':'+(e.state||'')+':'+(e.level||0)+':'+Math.floor(G.gold);if(!force&&key===lastInspector)return;lastInspector=key;
      if(e.kind==='flag'){panel.innerHTML='<div class="inspect-heading"><span class="eyebrow">A ROYAL DECREE</span><button class="inspect-close" aria-label="Close selection">×</button></div><div class="card-symbol" style="text-align:center;height:70px;font-size:57px">'+(e.type==='attack'?'⚑':'⚐')+'</div><h2 class="inspect-title">'+(e.type==='attack'?'Attack Bounty':'Explore Bounty')+'</h2><p class="inspect-subtitle">Gold speaks louder than orders</p><div class="inspect-stats"><span>Reward <strong>'+Math.floor(e.reward)+' gold</strong></span><span>Interested <strong>'+G.units.filter(u=>!u.dead&&u.hero&&u.goal===e).length+'</strong></span></div><p class="inspect-description">'+(e.target?'Defeat '+escape(e.target.data.name)+' to claim the reward.':'The first hero to reach this spot claims the reward.')+'</p><button id="raise-bounty" class="inspect-action" '+(G.gold<50?'disabled':'')+'>Raise reward &nbsp; +50 gold</button><button id="cancel-bounty" class="text-button">Withdraw bounty</button>';$('raise-bounty').onclick=()=>{G.raiseFlag(e);this.update(true);};$('cancel-bounty').onclick=()=>{G.cancelFlag(e);this.update(true);};}
      else{const b=e.kind==='building',label=b?(e.hostile?'MONSTER LAIR':e.progress<1?'UNDER CONSTRUCTION':'YOUR KINGDOM'):e.hero?'HERO OF ALDERWICK':e.hostile?'HOSTILE CREATURE':'SERVANT OF THE CROWN';panel.innerHTML='<div class="inspect-heading"><span class="eyebrow">'+label+'</span><button class="inspect-close" aria-label="Close selection">×</button></div><div class="inspect-portrait"><canvas aria-hidden="true"></canvas></div><h2 class="inspect-title">'+escape(b?e.data.name:e.name)+'</h2><p class="inspect-subtitle">'+escape(b?e.data.subtitle:(e.hero?'Level '+e.level+' '+e.data.name+' · ':'')+e.state)+'</p><div class="hp-label"><span>'+(b&&e.progress<1?'Construction '+Math.floor(e.progress*100)+'%':'Health')+'</span><span>'+Math.ceil(e.hp)+' / '+e.maxHp+'</span></div><div class="hp-track"><div class="hp-fill" style="width:'+G.clamp(e.hp/e.maxHp*100,0,100)+'%;'+(e.hostile?'background:#b57c60':'')+'"></div></div><div class="inspect-stats">'+(b?'<span>'+(e.hostile?'Bounty loot':'Tax reserves')+' <strong>'+Math.floor(e.data.reward||e.taxPool)+'g</strong></span><span>'+(e.type==='palace'?'Royal seat':e.progress<1?'Peasants at work':e.hostile?'Dangerous':'Operational')+'</span>':'<span>Attack <strong>'+(e.data.damage+(e.hero?(e.level-1)*4:0))+'</strong></span><span>'+(e.hero?'Purse <strong>'+Math.floor(e.gold)+'g</strong>':'Armor <strong>'+e.data.armor+'</strong>')+'</span>')+'</div><p class="inspect-description">'+escape(b?e.data.description:e.hero?(e.potions?'Carries '+e.potions+' healing potion'+(e.potions>1?'s':'')+'. ':'')+'Acts independently. Place bounties to encourage adventure.':e.type==='collector'?'Carries taxes back to the Palace. Keep the roads safe.':e.type==='peasant'?'Builds and repairs your kingdom automatically.':e.hostile?'A threat to your kingdom. Heroes and guards will fight it on sight.':'Patrols the Palace grounds and protects your subjects.')+'</p>'+(b&&e.data.recruits?'<button id="inspect-recruit" class="inspect-action" '+(e.progress<1?'disabled':'')+'>Recruit '+G.UNITS[e.data.recruits].name+' &nbsp; ✦ '+G.UNITS[e.data.recruits].cost+'</button>':'')+(e.hostile?'<button id="inspect-bounty" class="inspect-action">Post attack bounty &nbsp; ✦ 100</button>':'');this.thumbnail(panel.querySelector('canvas'),e.type,!b);if($('inspect-recruit'))$('inspect-recruit').onclick=()=>{G.recruit(e.data.recruits,e);this.update(true);};if($('inspect-bounty'))$('inspect-bounty').onclick=()=>{G.placeFlag('attack',e.x,e.y,e);this.update(true);};}
      panel.querySelector('.inspect-close').onclick=()=>{G.selected=null;this.updateInspector(true);};
    },
    openModal(html){wasPaused=G.paused;G.paused=true;G.modalOpen=true;G.keys={};$('modal-content').innerHTML=html;$('modal').classList.remove('hidden');$('modal-content').querySelector('button')?.focus();this.update(true);},
    closeModal(){if(G.result)return;$('modal').classList.add('hidden');G.modalOpen=false;G.paused=wasPaused;this.update(true);},
    showHelp(){if(G.modalOpen)return;this.openModal('<div class="eyebrow">A WORD FROM YOUR ADVISOR</div><h2>The art of ruling</h2><p>You are the monarch. Heroes make their own decisions — your buildings, bounties, and magic give them reasons to act.</p><ul><li><strong>Build a guild, then recruit.</strong> Select Construct, choose a building, and place it on clear ground. Peasants build it automatically. Recruit heroes once it is ready.</li><li><strong>Make adventure worthwhile.</strong> Place attack bounties on monsters and lairs, or exploration bounties in the wilderness. Select a flag to raise its reward.</li><li><strong>Keep the gold flowing.</strong> Heroes buy potions at the Marketplace. Tax collectors carry shop income and cottage taxes to your Palace.</li><li><strong>Protect your realm.</strong> Build towers and a Temple. Destroy all four lairs to win. Losing the Palace ends your reign.</li></ul><p><strong>Controls</strong><br>WASD / arrows or right-drag to pan · wheel to zoom<br>Space to pause · 1 / 2 / 3 for speed · F to center<br>Esc to cancel · Shift-click to place several buildings</p><button id="close-help" class="gold-button">Return to the kingdom <span>→</span></button>');$('close-help').onclick=()=>this.closeModal();},
    showEnd(result){const win=result==='victory';this.openModal('<div class="end-icon">'+(win?'♜':'♜')+'</div><div class="eyebrow">'+(win?'THE BORDERLANDS ARE FREE':'THE CROWN HAS FALLEN')+'</div><h2>'+(win?'Long live the sovereign.':'A kingdom remembered.')+'</h2><p>'+(win?'The last lair lies in ruins. Your heroes have brought peace to Alderwick, and your young kingdom has earned its place on the map.':'The Palace has fallen, but every sovereign learns. Raise more guilds, protect your roads, and let your next reign be a wiser one.')+'</p><div class="end-stats"><span>'+Math.floor(G.time/60)+':'+String(Math.floor(G.time%60)).padStart(2,'0')+'<small>YOUR REIGN</small></span><span>'+G.stats.lairs+' / 4<small>LAIRS DESTROYED</small></span><span>'+G.stats.recruited+'<small>HEROES RECRUITED</small></span></div><button id="restart" class="gold-button">A new beginning <span>→</span></button>');$('restart').onclick=()=>{G.result=null;G.modalOpen=false;$('modal').classList.add('hidden');G.reset();G.makeTerrain();G.centerCamera();tab='build';lastInspector='';this.update(true);};}
  };
})();
