import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
const gameUrl=process.env.SOVEREIGN_TEST_URL||new URL('../index.html',import.meta.url).href;
const tabs=await(await fetch('http://127.0.0.1:9227/json/list')).json();
const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);
let id=0;const pending=new Map(),errors=[];
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);};
const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});
const ev=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const clickXY=async(x,y)=>{await send('Input.dispatchMouseEvent',{type:'mouseMoved',x,y});await send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button:'left',clickCount:1});await delay(100);};
const click=async selector=>{const p=await ev(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`);await clickXY(p.x,p.y);};
const key=async(key,code)=>{await send('Input.dispatchKeyEvent',{type:'keyDown',key,code});await send('Input.dispatchKeyEvent',{type:'keyUp',key,code});await delay(100);};
const shot=async name=>fs.writeFile(path.join(os.tmpdir(),'sovereign-'+name+'.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
await send('Runtime.enable');await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await send('Page.navigate',{url:gameUrl});await delay(1500);
console.log('INITIAL',await ev('({sprites:Object.keys(G.sprites).length,buildings:G.buildings.length,units:G.units.length,welcome:G.welcoming,canvas:[document.querySelector("canvas").width,document.querySelector("canvas").height]})'));
await shot('welcome');
await click('#start');await delay(800);assert.equal(await ev('G.welcoming'),false);await key(' ','Space');assert.equal(await ev('G.paused'),true);await shot('game');
await click('.command-card');assert.equal(await ev('G.mode.key'),'warriors');const site=await ev('G.worldToScreen(16.25,18.25)');await clickXY(site.x,site.y);assert.equal(await ev('G.buildings.filter(b=>b.type==="warriors").length'),1);assert.equal(await ev('G.mode'),null);assert.equal(await ev('Math.floor(G.gold)'),1150);
await ev('G.paused=false;for(let t=0;t<30;t+=.1)G.update(.1);G.paused=true;G.ui.update(true)');assert.equal(await ev('G.buildings.find(b=>b.type==="warriors").progress'),1);
await click('#inspect-recruit');assert.equal(await ev('G.units.filter(u=>u.hero).length'),1);
await click('[data-tab="bounty"]');await click('.command-card:nth-child(2)');const spot=await ev('G.worldToScreen(25.5,23.5)');await clickXY(spot.x,spot.y);assert.equal(await ev('G.flags.filter(f=>!f.dead).length'),1);await click('#raise-bounty');assert.equal(await ev('G.flags[0].reward'),150);await click('#cancel-bounty');assert.equal(await ev('G.flags[0].dead'),true);
await click('[data-tab="spells"]');await click('.command-card:nth-child(3)');await clickXY(spot.x,spot.y);assert(await ev('G.cooldowns.farsight>0'));assert.equal(await ev('G.mode'),null);
await click('[data-speed="3"]');assert.equal(await ev('G.speed'),3);assert.equal(await ev('G.paused'),false);await key(' ','Space');assert.equal(await ev('G.paused'),true);
const zoom=await ev('G.camera.zoom');await click('#zoom-in');assert(await ev(`G.camera.zoom>${zoom}`));await key('f','KeyF');await click('#help');assert.equal(await ev('G.modalOpen'),true);await click('#close-help');assert.equal(await ev('G.modalOpen'),false);
console.log('✓ Real mouse and keyboard: start, pause, build, recruit, bounty placement/raise/refund, magic, speed, zoom, help.');
await send('Page.navigate',{url:gameUrl+'?auto=1&demo=2'});await delay(1300);await ev('G.paused=true;G.ui.update(true)');await shot('town');
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await send('Page.reload');await delay(1000);await ev('G.paused=true;G.ui.update(true)');await key('f','KeyF');await shot('mobile');assert.equal(await ev('document.documentElement.scrollWidth<=window.innerWidth'),true,'no horizontal viewport overflow');console.log('MOBILE',await ev('({width:innerWidth,height:innerHeight,deck:document.querySelector(".bottom-deck").getBoundingClientRect().toJSON(),inspector:document.querySelector("#inspector").getBoundingClientRect().toJSON()})'));
await click('[data-tab="bounty"]');assert.equal(await ev('document.querySelectorAll(".command-card").length'),2);await click('[data-tab="build"]');await shot('mobile');
assert.equal(errors.length,0,JSON.stringify(errors));console.log('✓ Desktop and mobile render with no JavaScript errors at '+gameUrl);
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await ws.close();
