import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
const url=process.env.SOVEREIGN_TEST_URL||'http://127.0.0.1:8123/';
const tabs=await(await fetch('http://127.0.0.1:9227/json/list')).json();
const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);
let id=0,loads=0;const pending=new Map(),errors=[];
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);else if(m.method==='Page.loadEventFired')loads++;};
const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});
const ev=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const load=async()=>{const previous=loads;await send('Page.navigate',{url:new URL('?seed=41972&auto=1',url).href});for(let i=0;i<200&&loads===previous;i++)await delay(100);assert(loads>previous);for(let i=0;i<200;i++){if(await ev('typeof G!=="undefined"&&typeof G.start==="function"')){await ev('Promise.all([G.spriteAssetsReady,document.fonts.ready]).then(()=>true)');await ev('G.paused=true;G.ui.update(true)');return;}await delay(100);}throw Error('Game did not load');};
const clickXY=async(x,y)=>{await send('Input.dispatchMouseEvent',{type:'mouseMoved',x,y});await send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button:'left',clickCount:1});};
const click=async selector=>{await ev(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({block:'center'})`);const p=await ev(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`);await clickXY(p.x,p.y);};
const shot=async name=>fs.writeFile(path.join(os.tmpdir(),'sovereign-'+name+'.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
try{
  await send('Runtime.enable');await send('Page.enable');errors.length=0;await send('Page.bringToFront');await send('Emulation.setFocusEmulationEnabled',{enabled:true});
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:2,mobile:false});await load();
  assert.equal(await ev('document.querySelector("#sanitation-status").textContent.includes("3 / 6 safe")'),true);
  await ev('G.selected=G.buildings.find(b=>b.hostile);G.ui.update(true)');
  assert(await ev('document.querySelector(".loot-preview").textContent.includes("45–75 gold")'));
  assert(await ev('document.querySelector(".inspect-stats").textContent.includes("Crown reward")'));
  await ev(`(()=>{const lair=G.selected;G.kill(lair,null);G.testChest=G.loot[0];for(const u of G.units)if(G.dist(u,lair)<12)u.dead=true;G.reveal(lair.x,lair.y,12);const rat=G.addUnit('rat',lair.x+3,lair.y+1);G.kill(rat,null);G.camera.zoom=2.1;const p=G.iso(lair.x,lair.y);G.camera.x=p.x;G.camera.y=p.y-20;G.selected=null;G.ui.update(true);G.render(0)})()`);
  assert(await ev('["loot_chest","loot_pouch"].every(k=>G.sprites[k].canvas.width===G.sprites[k].w*4&&!G.sprites[k].pixelArt)'));
  const pos=await ev('(()=>{const p=G.worldToScreen(G.testChest.x,G.testChest.y);return{x:p.x,y:p.y-8*G.camera.zoom}})()');await clickXY(pos.x,pos.y);
  assert.equal(await ev('G.selected===G.testChest'),true,'clicking a chest selects the recoverable loot');
  assert.equal(await ev('document.querySelector(".inspect-title").textContent'),'Treasure Chest');
  assert.equal(await ev('document.querySelector(".loot-stats strong").textContent'),await ev('G.testChest.gold+"g"'));
  assert(await ev('document.querySelector(".hero-supplies").textContent.includes("Healing")'));
  await shot('loot-desktop');
  await ev('G.tile(G.testChest.x,G.testChest.y).visible=false');assert.equal(await ev(`G.hitTest(${pos.x},${pos.y})===G.testChest`),false,'hidden loot cannot be selected');await ev('G.tile(G.testChest.x,G.testChest.y).visible=true');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});await ev('G.ui.update(true);G.render(0)');
  assert(await ev('(()=>{const r=document.querySelector(".loot-stats").getBoundingClientRect();return r.height>0&&r.right<=innerWidth})()'),'gold remains visible on phones');
  assert(await ev('document.documentElement.scrollWidth<=innerWidth'));await shot('loot-mobile');
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
  await ev(`(()=>{const p=G.testChest;G.testLootGold=p.gold;const start=G.nearPoint(p.x,p.y,3);G.testLooter=G.addUnit('thief',start.x,start.y,G.palace);G.headless=true;G.paused=false;for(let i=0;i<300&&!p.dead;i++)G.update(.1);G.headless=false;G.paused=true;G.selected=G.testLooter;G.ui.update(true)})()`);
  assert(await ev('G.testChest.dead&&G.testLooter.gold>=G.testLootGold&&G.testLooter.potions.healing>0'),'real hero AI recovers the chest');
  assert(await ev('document.querySelector(".hero-supplies").textContent.includes("Healing")'));
  await ev('G.result="victory";G.ui.showEnd("victory")');assert(await ev('document.querySelector(".loot-summary").textContent.includes(String(G.stats.lootGold))'));
  await ev('document.querySelector("#restart").click();G.paused=true');assert.equal(await ev('G.loot.length'),0);
  console.log('✓ Visible pouches/chests, drop previews, real selection, fog, mobile inventory, autonomous pickup and end-game totals.');

  await load();
  await ev('while(G.sanitationStatus().cottages<7){const p=G.findBuildingSite("house");G.addBuilding("house",p.x,p.y)}G.updateSanitation(59);G.ui.update(true)');
  assert.equal(await ev('document.querySelector("#sanitation-status").classList.contains("danger")'),true);
  assert(await ev('document.querySelector("#sanitation-status").textContent.includes("1s")'));
  await ev('G.updateSanitation(1);G.selected=G.buildings.find(b=>b.infestation&&!b.dead);G.reveal(G.selected.x,G.selected.y,10);const p=G.iso(G.selected.x,G.selected.y);G.camera.x=p.x;G.camera.y=p.y-20;G.camera.zoom=1.7;G.ui.update(true);G.render(0)');
  assert.equal(await ev('document.querySelector("#lair-count").textContent'),'0 / 8');
  assert.equal(await ev('document.querySelectorAll(".objective").length'),8);
  assert(await ev('document.querySelector("#sanitation-status").textContent.includes("1 active rat sewer")'));
  assert(await ev('document.querySelector(".loot-preview").textContent.includes("No loot")'));
  assert(await ev('G.units.filter(u=>u.infestation).length===2'));await shot('infestation-desktop');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});await ev('G.ui.update(true);G.render(0)');
  assert(await ev('document.documentElement.scrollWidth<=innerWidth'));assert(await ev('(()=>{const s=document.querySelector("#sanitation-status").getBoundingClientRect(),p=document.querySelector(".quest-panel").getBoundingClientRect();return s.height>0&&s.bottom<=p.bottom})()'));await shot('infestation-mobile');
  await ev('G.kill(G.selected,null);G.ui.update(true)');assert.equal(await ev('document.querySelector("#lair-count").textContent'),'0 / 8');assert.equal(await ev('G.loot.length'),0);
  await ev('G.selected=G.buildings.find(b=>b.type==="house"&&!b.dead);G.ui.update(true)');await click('#inspect-demolish');assert.equal(await ev('G.sanitationStatus().cottages'),6);assert(await ev('document.querySelector("#sanitation-status").textContent.includes("No overcrowding")'));
  assert.equal(errors.length,0,JSON.stringify(errors));console.log('✓ Overcrowding warnings, recurring sewer placement, rat outbreak, mobile status, no farmable drops and stable campaign objectives.');
}finally{await send('Emulation.clearDeviceMetricsOverride');ws.close();}
