import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
const url=process.env.SOVEREIGN_TEST_URL||'http://127.0.0.1:8123/';
const tabs=await(await fetch('http://127.0.0.1:9227/json/list')).json();
const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);
let id=0,loads=0;const pending=new Map(),errors=[];
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);else if(m.method==='Page.loadEventFired')loads++;};
const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});
const ev=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const load=async()=>{const previous=loads;await send('Page.navigate',{url:new URL('?seed=41972&auto=1',url).href});for(let i=0;i<200&&loads===previous;i++)await delay(100);assert(loads>previous);for(let i=0;i<200;i++){if(await ev('typeof G!=="undefined"&&typeof G.start==="function"')){await ev('Promise.all([G.spriteAssetsReady,document.fonts.ready]).then(()=>true)');await ev('G.paused=true;G.ui.update(true)');return;}await delay(100);}throw Error('Game did not load');};
const clickXY=async(x,y)=>{await send('Input.dispatchMouseEvent',{type:'mouseMoved',x,y});await send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button:'left',clickCount:1});};
const click=async selector=>{await ev(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({block:'center'})`);const p=await ev(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`);await clickXY(p.x,p.y);};
const shot=async name=>fs.writeFile(path.join(os.tmpdir(),'sovereign-'+name+'.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
try{
  await send('Runtime.enable');await send('Page.enable');errors.length=0;await send('Page.bringToFront');await send('Emulation.setFocusEmulationEnabled',{enabled:true});
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:2,mobile:false});await load();
  await ev(`G.gold=5000;const site=G.findBuildingSite('temple');G.testTemple=G.addBuilding('temple',site.x,site.y);G.selected=G.testTemple;G.ui.update(true)`);
  await click('#inspect-spellbook');
  assert.equal(await ev('document.querySelectorAll("[data-learn-spell]").length'),7);
  assert(await ev('document.querySelector("[data-learn-spell=frost]").disabled'));
  assert(await ev('document.querySelector("[data-learn-spell=farsight]").disabled'));
  assert(await ev('document.querySelector("#modal-content").textContent.includes("Wizard: 25 mana")'));
  await shot('spellbook-desktop');
  const money=await ev('G.gold');await click('[data-learn-spell=heal]');
  assert.equal(await ev('G.gold'),money-125);assert(await ev('G.paused&&!G.modalOpen'),'funding restores prior pause');
  assert.equal(await ev('G.magic.project.key'),'heal');
  assert(await ev('document.querySelector(".research-status").textContent.includes("Learning Healing Light")'));
  await ev('G.updateMagic(20);G.ui.update(true)');assert(await ev('G.spellAvailable("heal")'));
  await click('[data-tab=spells]');await click('[data-command=frost]');assert(await ev('G.modalOpen'),'locked spells open the Temple spellbook');
  await click('[data-learn-spell=lightning]');await ev('G.updateMagic(25);G.ui.update(true)');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});
  await click('#inspect-spellbook');assert(await ev('document.documentElement.scrollWidth<=innerWidth'));
  await click('[data-learn-spell=frost]');assert.equal(await ev('G.magic.project.key'),'frost');await ev('G.updateMagic(30);G.ui.update(true)');await click('#inspect-spellbook');await shot('spellbook-mobile');
  assert(await ev('document.querySelector("[data-learn-spell=meteor]").disabled===false'));
  await click('#close-spellbook');
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:2,mobile:false});
  await ev(`(()=>{
    const tile=G.tiles.find(t=>t.kind==='grass'&&t.visible&&!t.blocked&&G.dist(t,G.palace)>8&&G.dist(t,G.palace)<11);
    G.testArena={x:tile.x+.5,y:tile.y+.5};const a=G.testArena;G.trees=G.trees.filter(t=>G.dist(t,a)>4);
    for(const u of G.units)u.dead=true;
    G.testWizard=G.addUnit('wizard',a.x-1.8,a.y+1.2);G.testAlly=G.addUnit('warrior',a.x-.8,a.y+.3);G.testEnemy=G.addUnit('troll',a.x+1.5,a.y);
    G.testEnemy.target=G.testAlly;G.testWizard.target=G.testEnemy;G.testAlly.target=G.testEnemy;
    G.testAlly.hp=45;G.selected=G.testWizard;G.reveal(a.x,a.y,12);
    const p=G.iso(a.x,a.y);G.camera.x=p.x;G.camera.y=p.y-40;G.camera.zoom=1.55;
    G.ui.update(true);G.render(0);
  })()`);
  await click('[data-command=heal]');const pos=await ev('G.worldToScreen(G.testAlly.x,G.testAlly.y)');const paid=await ev('G.gold');await clickXY(pos.x,pos.y);
  assert.equal(await ev('G.gold'),paid-65);assert.equal(await ev('G.testAlly.hp'),175);assert.equal(await ev('G.mode'),null);assert(await ev('G.effects.some(e=>e.type==="spell"&&e.spell==="heal")'));
  await ev('G.testAlly.hp=30;G.paused=false;G.thinkWizard(G.testWizard);G.paused=true;G.ui.update(true)');
  assert.equal(await ev('G.testWizard.lastSpell.key'),'heal');assert.equal(await ev('G.testWizard.mana'),75);assert(await ev('document.querySelector(".wizard-magic").textContent.includes("75 / 100")'));
  assert(await ev('document.querySelector(".wizard-magic").textContent.includes("Last cast: Healing Light")'));
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});await ev('G.ui.update(true)');
  assert(await ev('(()=>{const r=document.querySelector(".wizard-magic").getBoundingClientRect();return r.width>0&&r.right<=innerWidth})()'));await shot('wizard-mana-mobile');
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:2,mobile:false});
  for(const [key,age]of Object.entries({heal:.55,lightning:.12,frost:.55,ward:.7,haste:.65,farsight:.55,meteor:.9})){
    await ev(`G.effects=[];G.spellEffect('${key}',G.testEnemy.x,G.testEnemy.y,G.testWizard);G.effects[0].started=G.time-${age};G.render(0)`);
    await shot('spell-'+key);
    const check=await ev(`(()=>{const e=G.effects[0],c=document.createElement('canvas');c.width=800;c.height=600;const ctx=c.getContext('2d'),p=G.iso(e.x,e.y);ctx.translate(400-p.x,400-p.y);G.magicArt.effect(ctx,e,${age});const first=c.toDataURL();ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,800,600);ctx.restore();G.magicArt.effect(ctx,e,${age}+.2);const second=c.toDataURL();const data=ctx.getImageData(0,0,800,600).data;let ink=0;for(let i=3;i<data.length;i+=4)if(data[i])ink++;return{different:first!==second,ink}})()`);
    assert(check.different&&check.ink>1000,key+' has animated detailed artwork');
  }
  await ev(`G.effects=[];G.spellEffect('meteor',G.testEnemy.x,G.testEnemy.y);G.effects[0].started=G.time-.4;G.render(0)`);await shot('meteor-descent');
  await ev(`for(const key of ['ward','haste']){G.magic.unlocked[key]=true;G.cooldowns[key]=0;G.cast(key,G.testAlly.x,G.testAlly.y)}G.magic.unlocked.frost=true;G.cooldowns.frost=0;G.cast('frost',G.testEnemy.x,G.testEnemy.y);G.effects=[];G.selected=G.testAlly;G.ui.update(true);G.render(0)`);
  assert(await ev('G.testAlly.magicBuffs.ward>0&&G.testAlly.magicBuffs.haste>0&&G.testEnemy.magicBuffs.frost>0'));
  assert(await ev('document.querySelector(".active-buffs").textContent.includes("Arcane Ward")'));await shot('spell-auras');
  await ev(`G.testLair=G.buildings.find(b=>b.hostile&&b.type==='graveyard');G.reveal(G.testLair.x,G.testLair.y,12);const p=G.iso(G.testLair.x,G.testLair.y);G.camera.x=p.x;G.camera.y=p.y-70;G.camera.zoom=1.3;G.selected=null;G.cooldowns.lightning=0;G.ui.update(true)`);
  await click('[data-command=lightning]');
  const roof=await ev(`(()=>{const b=G.testLair,l=G.buildingSpriteLayout(b.type),s=l.sprite,y=Math.floor(s.bounds[1]+(s.bounds[3]-s.bounds[1])*.3),row=s.hitRows[y],x=(row[0]+row[1])/2,p=G.worldToScreen(b.x,b.y);return{x:p.x+(l.x+x*l.scale)*G.camera.zoom,y:p.y+(l.y+y*l.scale)*G.camera.zoom}})()`);
  assert(await ev(`G.hitTest(${roof.x},${roof.y})===G.testLair`));const lairHP=await ev('G.testLair.hp');await clickXY(roof.x,roof.y);
  assert.equal(await ev('G.testLair.hp'),lairHP-190,'clicking a tall lair targets its foundation, with the preview and impact aligned');
  const frozen=await ev('G.time');await delay(350);assert.equal(await ev('G.time'),frozen,'spell animation clock freezes when paused');
  assert.equal(errors.length,0,JSON.stringify(errors));console.log('✓ Desktop/mobile Temple research, prerequisites, real player casting, wizard mana, every spell animation, status auras and pause.');
}finally{await send('Emulation.clearDeviceMetricsOverride');ws.close();}
