"""Export cropped high-resolution textures, hit shapes, effect anchors and a gallery."""

import argparse
import hashlib
import json
import math
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

from finish_palace import font, version_runtime_scripts

ROOT=Path(__file__).resolve().parents[2]
KEYS=("warriors","rangers","wizards","marketplace","temple","tower","house","sewer","graveyard","goblin")


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument("--source",type=Path,default=ROOT/"assets/art/buildings/source")
    parser.add_argument("--output",type=Path,default=ROOT/"assets/art/buildings")
    parser.add_argument("--no-integrate",action="store_true")
    args=parser.parse_args()
    args.output.mkdir(parents=True,exist_ok=True)
    assets={}
    info={}
    previews=[]
    for key in KEYS:
        meta=json.loads((args.source/f"{key}.json").read_text())
        source=Image.open(args.source/f"{key}-render.png").convert("RGBA")
        ratio=source.width/240
        anchor=[v*source.width for v in meta["ground_anchor_normalized"]]
        shadow=Image.new("RGBA",source.size)
        d=ImageDraw.Draw(shadow)
        radius=(3.1 if meta["plot_size"]==1 else 6.2)*.7071/14.3*source.width
        for factor,alpha in ((1.06,18),(.93,26)):
            rx,ry=radius*factor,radius*factor*.5
            d.ellipse((anchor[0]-rx,anchor[1]-ry,anchor[0]+rx,anchor[1]+ry),fill=(25,39,32,alpha))
        shadow=shadow.filter(ImageFilter.GaussianBlur(source.width*.0035))
        combined=Image.alpha_composite(shadow,source)
        # Crop only transparent margins, preserving every rendered pixel and its density.
        bb=combined.getbbox()
        step=max(1,round(ratio))
        pad=step*2
        crop=(max(0,math.floor((bb[0]-pad)/step)*step),max(0,math.floor((bb[1]-pad)/step)*step),
              min(source.width,math.ceil((bb[2]+pad)/step)*step),min(source.height,math.ceil((bb[3]+pad)/step)*step))
        sprite=combined.crop(crop)
        path=args.output/f"{key}.png"
        sprite.save(path,optimize=True)
        w,h=sprite.width/ratio,sprite.height/ratio
        source_alpha=source.crop(crop).getchannel("A")
        solid=source_alpha.point(lambda x:255 if x>=96 else 0)
        bounds=[v/ratio for v in solid.getbbox()]
        mask=source_alpha.resize((math.ceil(w),math.ceil(h)),Image.Resampling.LANCZOS)
        rows=[]
        for y in range(mask.height):
            row=list(mask.crop((0,y,mask.width,y+1)).get_flattened_data())
            occupied=[x for x,a in enumerate(row) if a>=64]
            rows.append([occupied[0],occupied[-1]+1] if occupied else None)
        runtime={"w":w,"h":h,"anchor":[(anchor[0]-crop[0])/ratio,(anchor[1]-crop[1])/ratio],
                 "bounds":bounds,"pixelArt":False,"sourceSize":list(sprite.size),"hitRows":rows,
                 "effects":[{"type":e["type"],"at":[(e["at_normalized"][0]*source.width-crop[0])/ratio,
                                                       (e["at_normalized"][1]*source.height-crop[1])/ratio]}
                            for e in meta["effects"]]}
        digest=hashlib.sha256(path.read_bytes()).hexdigest()[:12]
        assets[key]=dict(runtime,src=f"{key}.png?v={digest}")
        info[key]={"name":meta["name"],"image":f"{key}.png","scene":f"source/{key}.blend",
                   "master_render_size":list(source.size),"crop":list(crop),**runtime}
        previews.append((meta["name"],sprite))
        assert len(rows)==math.ceil(h) and any(rows)
        assert source.width==source.height and source.width>=640
        assert all(0<v<source.width for v in source.getchannel("A").getbbox()),key+" clipped"
        print(f"{key}: {source.width}² render → {sprite.width}×{sprite.height} texture; logical {w:g}×{h:g}")
    manifest="// Generated by tools/art/finish_buildings.py.\n(function () {\n"
    manifest+="  const assets = "+json.dumps(assets,separators=(",",":"))+";\n"
    manifest+="  G.spriteAssets = G.spriteAssets || {};\n"
    manifest+="  for (const [key,asset] of Object.entries(assets)) {\n"
    manifest+="    asset.src = new URL(asset.src, document.currentScript.src).href;\n"
    manifest+="    G.spriteAssets[key] = asset;\n  }\n})();\n"
    (args.output/"buildings-sprites.js").write_text(manifest)
    (args.output/"buildings.json").write_text(json.dumps(info,indent=2)+"\n")
    board=Image.new("RGBA",(1900,1120),(34,51,43,255))
    d=ImageDraw.Draw(board)
    d.text((950,43),"S O V E R E I G N   /   T H E   B O R D E R L A N D S",font=font(27,True),fill="#e8dbc0",anchor="mm")
    d.text((950,81),"KINGDOM BUILDINGS & MONSTER LAIRS  ·  TERRACOTTA / WEATHERED STONE / CRIMSON",font=font(13),fill="#aebba0",anchor="mm")
    for i,(name,sprite) in enumerate(previews):
        x,y=(i%5)*380,(i//5)*490+112
        d.rounded_rectangle((x+12,y,x+368,y+471),radius=5,fill="#2d4338",outline="#697253")
        img=sprite.copy()
        img.thumbnail((332,373),Image.Resampling.LANCZOS)
        board.alpha_composite(img,(x+(380-img.width)//2,y+18+(373-img.height)//2))
        d.text((x+190,y+428),name,font=font(20,True),fill="#e3d7bc",anchor="mm")
    board.convert("RGB").save(args.output/"buildings-preview.png")
    if not args.no_integrate:
        version_runtime_scripts()


if __name__=="__main__":
    main()
